console.log("why you are reading logs, Are you trying to copy code huh!");
function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}
window.onclick = function(e) {
  if (!e.target.matches('.dropbtn')) {
  var myDropdown = document.getElementById("myDropdown");
    if (myDropdown.classList.contains('show')) {
      myDropdown.classList.remove('show');
    }
  }
}
function anime(){
  document.getElementById("animediv").style.display="block";
  document.getElementById("infodiv").style.display="none";
  document.getElementById("supportdiv").style.display="none";
  document.getElementById("configdiv").style.display="none";
  document.getElementById("economydiv").style.display="none";
  document.getElementById("fundiv").style.display="none";
  document.getElementById("gamediv").style.display="none";
  document.getElementById("generaldiv").style.display="none";
  document.getElementById("lmaoimg").style.display="none";
  document.getElementById("moderationdiv").style.display="none";
  document.getElementById("pokemondiv").style.display="none";
  document.getElementById("serverdiv").style.display="none";
  document.getElementById("xpdiv").style.display="none";
  document.getElementById("otherdiv").style.display="none";
}
function info(){
  document.getElementById("animediv").style.display="none";
  document.getElementById("infodiv").style.display="block";
  document.getElementById("supportdiv").style.display="none";
  document.getElementById("configdiv").style.display="none";
  document.getElementById("economydiv").style.display="none";
  document.getElementById("fundiv").style.display="none";
  document.getElementById("gamediv").style.display="none";
  document.getElementById("generaldiv").style.display="none";
  document.getElementById("lmaoimg").style.display="none";
  document.getElementById("moderationdiv").style.display="none";
  document.getElementById("pokemondiv").style.display="none";
  document.getElementById("serverdiv").style.display="none";
  document.getElementById("xpdiv").style.display="none";
  document.getElementById("otherdiv").style.display="none";
}
function support(){
  document.getElementById("animediv").style.display="none";
  document.getElementById("infodiv").style.display="none";
  document.getElementById("supportdiv").style.display="block";
  document.getElementById("configdiv").style.display="none";
  document.getElementById("economydiv").style.display="none";
  document.getElementById("fundiv").style.display="none";
  document.getElementById("gamediv").style.display="none";
  document.getElementById("generaldiv").style.display="none";
  document.getElementById("lmaoimg").style.display="none";
  document.getElementById("moderationdiv").style.display="none";
  document.getElementById("pokemondiv").style.display="none";
  document.getElementById("serverdiv").style.display="none";
  document.getElementById("xpdiv").style.display="none";
  document.getElementById("otherdiv").style.display="none";
}
function config(){
  document.getElementById("animediv").style.display="none";
  document.getElementById("infodiv").style.display="none";
  document.getElementById("supportdiv").style.display="none";
  document.getElementById("configdiv").style.display="block";
  document.getElementById("economydiv").style.display="none";
  document.getElementById("fundiv").style.display="none";
  document.getElementById("gamediv").style.display="none";
  document.getElementById("generaldiv").style.display="none";
  document.getElementById("lmaoimg").style.display="none";
  document.getElementById("moderationdiv").style.display="none";
  document.getElementById("pokemondiv").style.display="none";
  document.getElementById("serverdiv").style.display="none";
  document.getElementById("xpdiv").style.display="none";
  document.getElementById("otherdiv").style.display="none";
}
function economy(){
  document.getElementById("animediv").style.display="none";
  document.getElementById("infodiv").style.display="none";
  document.getElementById("supportdiv").style.display="none";
  document.getElementById("configdiv").style.display="none";
  document.getElementById("economydiv").style.display="block";
  document.getElementById("fundiv").style.display="none";
  document.getElementById("gamediv").style.display="none";
  document.getElementById("generaldiv").style.display="none";
  document.getElementById("lmaoimg").style.display="none";
  document.getElementById("moderationdiv").style.display="none";
  document.getElementById("pokemondiv").style.display="none";
  document.getElementById("serverdiv").style.display="none";
  document.getElementById("xpdiv").style.display="none";
  document.getElementById("otherdiv").style.display="none";
}
function fun(){
  document.getElementById("animediv").style.display="none";
  document.getElementById("infodiv").style.display="none";
  document.getElementById("supportdiv").style.display="none";
  document.getElementById("configdiv").style.display="none";
  document.getElementById("economydiv").style.display="none";
  document.getElementById("fundiv").style.display="block";
  document.getElementById("gamediv").style.display="none";
  document.getElementById("generaldiv").style.display="none";
  document.getElementById("lmaoimg").style.display="none";
  document.getElementById("moderationdiv").style.display="none";
  document.getElementById("pokemondiv").style.display="none";
  document.getElementById("serverdiv").style.display="none";
  document.getElementById("xpdiv").style.display="none";
  document.getElementById("otherdiv").style.display="none";
}
function game(){
  document.getElementById("animediv").style.display="none";
  document.getElementById("infodiv").style.display="none";
  document.getElementById("supportdiv").style.display="none";
  document.getElementById("configdiv").style.display="none";
  document.getElementById("economydiv").style.display="none";
  document.getElementById("fundiv").style.display="none";
  document.getElementById("gamediv").style.display="block";
  document.getElementById("generaldiv").style.display="none";
  document.getElementById("lmaoimg").style.display="none";
  document.getElementById("moderationdiv").style.display="none";
  document.getElementById("pokemondiv").style.display="none";
  document.getElementById("serverdiv").style.display="none";
  document.getElementById("xpdiv").style.display="none";
  document.getElementById("otherdiv").style.display="none";
}
function general(){
  document.getElementById("animediv").style.display="none";
  document.getElementById("infodiv").style.display="none";
  document.getElementById("supportdiv").style.display="none";
  document.getElementById("configdiv").style.display="none";
  document.getElementById("economydiv").style.display="none";
  document.getElementById("fundiv").style.display="none";
  document.getElementById("gamediv").style.display="none";
  document.getElementById("generaldiv").style.display="block";
  document.getElementById("lmaoimg").style.display="none";
  document.getElementById("moderationdiv").style.display="none";
  document.getElementById("pokemondiv").style.display="none";
  document.getElementById("serverdiv").style.display="none";
  document.getElementById("xpdiv").style.display="none";
  document.getElementById("otherdiv").style.display="none";
}
function image(){
  document.getElementById("animediv").style.display="none";
  document.getElementById("infodiv").style.display="none";
  document.getElementById("supportdiv").style.display="none";
  document.getElementById("configdiv").style.display="none";
  document.getElementById("economydiv").style.display="none";
  document.getElementById("fundiv").style.display="none";
  document.getElementById("gamediv").style.display="none";
  document.getElementById("generaldiv").style.display="none";
  document.getElementById("lmaoimg").style.display="block";
  document.getElementById("moderationdiv").style.display="none";
  document.getElementById("pokemondiv").style.display="none";
  document.getElementById("serverdiv").style.display="none";
  document.getElementById("xpdiv").style.display="none";
  document.getElementById("otherdiv").style.display="none";
}function moderation(){
  document.getElementById("animediv").style.display="none";
  document.getElementById("infodiv").style.display="none";
  document.getElementById("supportdiv").style.display="none";
  document.getElementById("configdiv").style.display="none";
  document.getElementById("economydiv").style.display="none";
  document.getElementById("fundiv").style.display="none";
  document.getElementById("gamediv").style.display="none";
  document.getElementById("generaldiv").style.display="none";
  document.getElementById("lmaoimg").style.display="none";
  document.getElementById("moderationdiv").style.display="block";
  document.getElementById("pokemondiv").style.display="none";
  document.getElementById("serverdiv").style.display="none";
  document.getElementById("xpdiv").style.display="none";
  document.getElementById("otherdiv").style.display="none";
}
function pokemon(){
  document.getElementById("animediv").style.display="none";
  document.getElementById("infodiv").style.display="none";
  document.getElementById("supportdiv").style.display="none";
  document.getElementById("configdiv").style.display="none";
  document.getElementById("economydiv").style.display="none";
  document.getElementById("fundiv").style.display="none";
  document.getElementById("gamediv").style.display="none";
  document.getElementById("generaldiv").style.display="none";
  document.getElementById("lmaoimg").style.display="none";
  document.getElementById("moderationdiv").style.display="none";
  document.getElementById("pokemondiv").style.display="block";
  document.getElementById("serverdiv").style.display="none";
  document.getElementById("xpdiv").style.display="none";
  document.getElementById("otherdiv").style.display="none";
}
function server(){
  document.getElementById("animediv").style.display="none";
  document.getElementById("infodiv").style.display="none";
  document.getElementById("supportdiv").style.display="none";
  document.getElementById("configdiv").style.display="none";
  document.getElementById("economydiv").style.display="none";
  document.getElementById("fundiv").style.display="none";
  document.getElementById("gamediv").style.display="none";
  document.getElementById("generaldiv").style.display="none";
  document.getElementById("lmaoimg").style.display="none";
  document.getElementById("moderationdiv").style.display="none";
  document.getElementById("pokemondiv").style.display="none";
  document.getElementById("serverdiv").style.display="block";
  document.getElementById("xpdiv").style.display="none";
  document.getElementById("otherdiv").style.display="none";
}
function xp(){
  document.getElementById("animediv").style.display="none";
  document.getElementById("infodiv").style.display="none";
  document.getElementById("supportdiv").style.display="none";
  document.getElementById("configdiv").style.display="none";
  document.getElementById("economydiv").style.display="none";
  document.getElementById("fundiv").style.display="none";
  document.getElementById("gamediv").style.display="none";
  document.getElementById("generaldiv").style.display="none";
  document.getElementById("lmaoimg").style.display="none";
  document.getElementById("moderationdiv").style.display="none";
  document.getElementById("pokemondiv").style.display="none";
  document.getElementById("serverdiv").style.display="none";
  document.getElementById("xpdiv").style.display="block";
  document.getElementById("otherdiv").style.display="none";
}function other(){
  document.getElementById("animediv").style.display="none";
  document.getElementById("infodiv").style.display="none";
  document.getElementById("supportdiv").style.display="none";
  document.getElementById("configdiv").style.display="none";
  document.getElementById("economydiv").style.display="none";
  document.getElementById("fundiv").style.display="none";
  document.getElementById("gamediv").style.display="none";
  document.getElementById("generaldiv").style.display="none";
  document.getElementById("lmaoimg").style.display="none";
  document.getElementById("moderationdiv").style.display="none";
  document.getElementById("pokemondiv").style.display="none";
  document.getElementById("serverdiv").style.display="none";
  document.getElementById("xpdiv").style.display="none";
  document.getElementById("otherdiv").style.display="block";
}